<footer>
    <div id="contact-area">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h3 class="main-title">Entre em contato conosco</h3>
                </div>
                <div class="col-md-4 contact-box">
                    <i class="fa fa-phone" aria-hidden="true"></i>
                    <p><span class="contact-tile">Ligue para:</span> (16)99999-9999</p>
                    <p><span class="contact-tile">Horários:</span> 18:00 - 00:00</p>
                </div>
                <div class="col-md-4 contact-box">
                    <i class="fa fa-envelope" aria-hidden="true" aria-hidden="true"></i>
                    <p><span class="contact-tile">Envie um email:</span> contato@brooks.com.br</p>
                </div>
                <div class="col-md-4 contact-box">
                    <i class="fa fa-map-marker" aria-hidden="true"></i>
                    <p><span class="contact-tile">Venha pessoalmente:</span> Rua Alberto Benassi, Santa Angelina - 1314</p>
                </div>
                <div class="col-md-6" id="msg-box">
                    <p>Ou nos deixe uma mensagem:</p>
                </div>
                <div class="col-md-6" id="contact-form">
                    <form action="">
                        <input type="text" class="form-control" placeholder="E-mail" name="email">
                        <input type="text" class="form-control" placeholder="Assunto" name="subject">
                        <textarea class="form-control" rows="3" placeholder="Sua mensagem..." name="message"></textarea>
                        <input type="submit" class="btn btn-outline-warning">
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div id="copy-area">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p>Desenvolvido por <a href="" target="_blank">Sabrina Zanella e Vinícius Maiores</a> &copy; 2021</p>
                </div>
            </div>
        </div>
    </div>
</footer>